# Config :)
Map: Testing World
DatabaseMapName: LushRush # The name of the map in the database and in the server
MapName: LushRush
ServerIP: alpha.foxikle.dev
Mode: 4v4v4v4
MinPlayers: 8
MaxPlayers: 16
BridgeEggBlockDespawn: 3600
BridgeEggBlockLimit: 32
WorldSpawn:
  x: 3
  y: 125
  z: 3
SpawnPlatformCenter:
  world: LushRush
  x: 3
  y: 123
  z: 4
  pitch: 0.0
  yaw: 0.0

Teams:
  Red Team:
    TAB_PREFIX: '&c[R] '
    TEAM_COLOR: RED
    BED_ITEM: RED_BED
    GLASS_ITEM: RED_STAINED_GLASS
    WOOL_ITEM: RED_WOOL
    TERRACOTTA_ITEM: RED_TERRACOTTA
    SPAWN_LOCATION:
      world: LushRush
      x: -58.5
      y: 52.0
      z: 8.5
      pitch: 0.0
      yaw: -90.0

    GENERATOR_LOCATION:
      world: LushRush
      x: -62.0
      y: 51.0
      z: 3.0
      pitch: 0.0
      yaw: 0.0

    ITEM_SHOP_LOCATION:
      world: LushRush
      x: -64.5
      y: 51
      z: 7.5
      pitch: 0.0
      yaw: -90.0

    TEAM_SHOP_LOCATION:
      world: LushRush
      x: -64.5
      y: 51
      z: 9.5
      pitch: 0.0
      yaw: -90.0

    TEAM_CHEST_LOCATION:
      world: LushRush
      x: 0.0
      y: 0.0
      z: 0.0
      pitch: 90.0
      yaw: 0.0

  Yellow Team:
    TAB_PREFIX: '&e[Y] '
    TEAM_COLOR: YELLOW
    BED_ITEM: YELLOW_BED
    GLASS_ITEM: YELLOW_STAINED_GLASS
    WOOL_ITEM: YELLOW_WOOL
    TERRACOTTA_ITEM: YELLOW_TERRACOTTA
    SPAWN_LOCATION:
      world: LushRush
      x: 7.5
      y: 52.0
      z: -57.5
      pitch: 0.0
      yaw: 0.0

    GENERATOR_LOCATION:
      world: LushRush
      x: 13.0
      y: 51.0
      z: -61.0
      pitch: 0.0
      yaw: 0.0

    ITEM_SHOP_LOCATION:
      world: LushRush
      x: 8.5
      y: 51.0
      z: -63.5
      pitch: 0.0
      yaw: 0.0

    TEAM_SHOP_LOCATION:
      world: LushRush
      x: 6.5
      y: 51.0
      z: -63.5
      pitch: 90.0
      yaw: 0.0

    TEAM_CHEST_LOCATION:
      world: LushRush
      x: 0.0
      y: 0.0
      z: 0.0
      pitch: 90.0
      yaw: 0.0

  Blue Team:
    TAB_PREFIX: '&9[B] '
    TEAM_COLOR: BLUE
    BED_ITEM: BLUE_BED
    GLASS_ITEM: BLUE_STAINED_GLASS
    WOOL_ITEM: BLUE_WOOL
    TERRACOTTA_ITEM: BLUE_TERRACOTTA
    SPAWN_LOCATION:
      world: LushRush
      x: 7.5
      y: 52.5
      z: 73.5
      pitch: 0.0
      yaw: 180.0

    GENERATOR_LOCATION:
      world: LushRush
      x: 2.0
      y: 51.0
      z: 77.0
      pitch: 90.0
      yaw: 0.0

    ITEM_SHOP_LOCATION:
      world: LushRush
      x: 6.5
      y: 51.0
      z: 79.5
      pitch: 0.0
      yaw: 180.0

    TEAM_SHOP_LOCATION:
      world: LushRush
      x: 8.5
      y: 51.0
      z: 79.5
      pitch: 90.0
      yaw: 180.0

    TEAM_CHEST_LOCATION:
      world: LushRush
      x: 0.0
      y: 0.0
      z: 0.0
      pitch: 90.0
      yaw: 0.0

  Green Team:
    TAB_PREFIX: '&a[G] '
    TEAM_COLOR: GREEN
    BED_ITEM: LIME_BED
    GLASS_ITEM: LIME_STAINED_GLASS
    WOOL_ITEM: LIME_WOOL
    TERRACOTTA_ITEM: LIME_TERRACOTTA
    SPAWN_LOCATION:
      world: LushRush
      x: 73.5
      y: 52.0
      z: 8.5
      pitch: 0.0
      yaw: 90.0

    GENERATOR_LOCATION:
      world: LushRush
      x: 77.0
      y: 51.0
      z: 14.0
      pitch: 0.0
      yaw: 0.0

    ITEM_SHOP_LOCATION:
      world: LushRush
      x: 79.5
      y: 51.0
      z: 9.5
      pitch: 0.0
      yaw: 90.0

    TEAM_SHOP_LOCATION:
      world: LushRush
      x: 79.5
      y: 51.0
      z: 7.5
      pitch: 0.0
      yaw: 90.0

    TEAM_CHEST_LOCATION:
      world: LushRush
      x: 0.0
      y: 0.0
      z: 0.0
      pitch: 90.0
      yaw: 0.0
