name: WebNetBedWars
version: '${version}'
description: 'stuff'
authors:
  - Foxikle
  - Webhead1104
main: dev.foxikle.webnetbedwars.WebNetBedWars
api-version: '1.20'
commands:
  debug:
    description: Debugging command :)
