name: WebNetBedWars
version: '${version}'
description: 'stuff'
authors:
  - Foxikle
  - Webhead1104
main: dev.foxikle.webnetbedwars.WebNetBedWars
api-version: '1.20'
depend:
  - CustomNPCs
  - SlimeWorldManager
commands:
  debug:
    description: Debugging command :)
  item:
    description: A command to give you items
    aliases:
      - i
  openitemshop:
    description: Opens the item shop
permissions:
  webnet.bedwars.*:
    default: op
    description: A wildcard permission
    children:
      - webnet.bedwars.item_command
      - webnet.bedwars.debug
  webnet.bedwars.item_command:
    description: A permission to use the /item command
    default: op
  webnet.bedwars.debug:
    description: A permission to use the /debug command
