package dev.foxikle.webnetbedwars.managers;

import com.infernalsuite.aswm.api.SlimePlugin;
import com.infernalsuite.aswm.api.exceptions.CorruptedWorldException;
import com.infernalsuite.aswm.api.exceptions.NewerFormatException;
import com.infernalsuite.aswm.api.exceptions.UnknownWorldException;
import com.infernalsuite.aswm.api.exceptions.WorldLockedException;
import com.infernalsuite.aswm.api.loaders.SlimeLoader;
import com.infernalsuite.aswm.api.world.SlimeWorld;
import com.infernalsuite.aswm.api.world.properties.SlimeProperties;
import com.infernalsuite.aswm.api.world.properties.SlimePropertyMap;
import dev.foxikle.webnetbedwars.WebNetBedWars;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;

import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Level;

import static org.bukkit.Material.AIR;

public class WorldManager {
    private final WebNetBedWars plugin;
    private final GameManager gameManager;
    private SlimeWorld world;

    public WorldManager(WebNetBedWars plugin, GameManager gameManager) {
        this.plugin = plugin;
        this.gameManager = gameManager;
    }

    public void createSpawnPlatform() {
        Location loc = plugin.getLocation("SpawnPlatformCenter");
        int x = (int) loc.getX();
        int y = (int) loc.getY();
        int z = (int) loc.getZ();
        World world = loc.getWorld();
        world.setSpawnLocation(loc);

        Bukkit.getScheduler().runTask(plugin, () -> {
            world.getBlockAt(x, y, z).setType(Material.BEACON);
            world.getBlockAt(x + 1, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 5, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 5, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 5, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 5, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 5, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 5, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z - 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z - 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z - 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z + 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z + 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z + 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y + 1, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE); // WALLS V LAYER 1
            world.getBlockAt(x + 1, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 2, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 1, z - 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x + 4, y + 1, z - 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 1, z - 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 1, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 5, y + 1, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 1, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 2, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 1, z - 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x - 4, y + 1, z - 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 1, z - 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 1, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 1, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 1, y + 1, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 1, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 2, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 1, z + 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x + 4, y + 1, z + 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 1, z + 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 1, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 5, y + 1, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 1, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 2, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 1, z + 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x - 4, y + 1, z + 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 1, z + 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 1, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 1, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 1, z).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x + 5, y + 1, z).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x, y + 1, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x, y + 1, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x + 1, y + 2, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE); // WALLS LAYER 2 V
            world.getBlockAt(x + 1, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 2, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 2, z - 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x + 4, y + 2, z - 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 2, z - 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 2, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 5, y + 2, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 2, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 2, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 2, z - 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x - 4, y + 2, z - 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 2, z - 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 2, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 2, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 1, y + 2, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 1, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 2, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 2, z + 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x + 4, y + 2, z + 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 2, z + 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 2, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 5, y + 2, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 2, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 2, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 2, z + 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x - 4, y + 2, z + 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 2, z + 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 2, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 2, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 2, z).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x + 5, y + 2, z).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x, y + 2, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x, y + 2, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x - 3, y + 3, z + 2).setType(Material.DARK_PRISMARINE_SLAB);// ROOF V
            world.getBlockAt(x - 3, y + 3, z + 1).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 2, y + 3, z + 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 1, y + 3, z + 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 3, y + 3, z - 2).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 3, y + 3, z - 1).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 2, y + 3, z - 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 1, y + 3, z - 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 3, y + 3, z + 2).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 3, y + 3, z + 1).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 2, y + 3, z + 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 1, y + 3, z + 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 3, y + 3, z - 2).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 3, y + 3, z - 1).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 2, y + 3, z - 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 1, y + 3, z - 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 4, y + 3, z).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 4, y + 3, z).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x, y + 3, z + 4).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x, y + 3, z - 4).setType(Material.DARK_PRISMARINE_SLAB);
        });
    }

    //fixme use a for loop or recusion to simplify
    public void removeSpawnPlatform() {
        Location loc = plugin.getLocation("SpawnPlatformCenter");
        int x = (int) loc.getX();
        int y = (int) loc.getY();
        int z = (int) loc.getZ();
        World world = loc.getWorld();

        Bukkit.getScheduler().runTask(plugin, () -> {
            world.getBlockAt(x, y, z).setType(AIR);
            world.getBlockAt(x + 1, y, z).setType(AIR);
            world.getBlockAt(x + 2, y, z).setType(AIR);
            world.getBlockAt(x + 3, y, z).setType(AIR);
            world.getBlockAt(x + 4, y, z).setType(AIR);
            world.getBlockAt(x + 5, y, z).setType(AIR);
            world.getBlockAt(x - 1, y, z).setType(AIR);
            world.getBlockAt(x - 2, y, z).setType(AIR);
            world.getBlockAt(x - 3, y, z).setType(AIR);
            world.getBlockAt(x - 4, y, z).setType(AIR);
            world.getBlockAt(x - 5, y, z).setType(AIR);
            world.getBlockAt(x, y, z + 1).setType(AIR);
            world.getBlockAt(x + 1, y, z + 1).setType(AIR);
            world.getBlockAt(x + 2, y, z + 1).setType(AIR);
            world.getBlockAt(x + 3, y, z + 1).setType(AIR);
            world.getBlockAt(x + 4, y, z + 1).setType(AIR);
            world.getBlockAt(x + 5, y, z + 1).setType(AIR);
            world.getBlockAt(x - 1, y, z + 1).setType(AIR);
            world.getBlockAt(x - 2, y, z + 1).setType(AIR);
            world.getBlockAt(x - 3, y, z + 1).setType(AIR);
            world.getBlockAt(x - 4, y, z + 1).setType(AIR);
            world.getBlockAt(x - 5, y, z + 1).setType(AIR);
            world.getBlockAt(x, y, z - 1).setType(AIR);
            world.getBlockAt(x + 1, y, z - 1).setType(AIR);
            world.getBlockAt(x + 2, y, z - 1).setType(AIR);
            world.getBlockAt(x + 3, y, z - 1).setType(AIR);
            world.getBlockAt(x + 4, y, z - 1).setType(AIR);
            world.getBlockAt(x + 5, y, z - 1).setType(AIR);
            world.getBlockAt(x - 1, y, z - 1).setType(AIR);
            world.getBlockAt(x - 2, y, z - 1).setType(AIR);
            world.getBlockAt(x - 3, y, z - 1).setType(AIR);
            world.getBlockAt(x - 4, y, z - 1).setType(AIR);
            world.getBlockAt(x - 5, y, z - 1).setType(AIR);
            world.getBlockAt(x, y, z - 2).setType(AIR);
            world.getBlockAt(x + 1, y, z - 2).setType(AIR);
            world.getBlockAt(x + 2, y, z - 2).setType(AIR);
            world.getBlockAt(x + 3, y, z - 2).setType(AIR);
            world.getBlockAt(x + 4, y, z - 2).setType(AIR);
            world.getBlockAt(x - 1, y, z - 2).setType(AIR);
            world.getBlockAt(x - 2, y, z - 2).setType(AIR);
            world.getBlockAt(x - 3, y, z - 2).setType(AIR);
            world.getBlockAt(x - 4, y, z - 2).setType(AIR);
            world.getBlockAt(x, y, z - 3).setType(AIR);
            world.getBlockAt(x + 1, y, z - 3).setType(AIR);
            world.getBlockAt(x + 2, y, z - 3).setType(AIR);
            world.getBlockAt(x + 3, y, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y, z - 3).setType(AIR);
            world.getBlockAt(x - 1, y, z - 3).setType(AIR);
            world.getBlockAt(x - 2, y, z - 3).setType(AIR);
            world.getBlockAt(x - 3, y, z - 3).setType(AIR);
            world.getBlockAt(x - 4, y, z - 3).setType(AIR);
            world.getBlockAt(x, y, z + 2).setType(AIR);
            world.getBlockAt(x + 1, y, z + 2).setType(AIR);
            world.getBlockAt(x + 2, y, z + 2).setType(AIR);
            world.getBlockAt(x + 3, y, z + 2).setType(AIR);
            world.getBlockAt(x + 4, y, z + 2).setType(AIR);
            world.getBlockAt(x - 1, y, z + 2).setType(AIR);
            world.getBlockAt(x - 2, y, z + 2).setType(AIR);
            world.getBlockAt(x - 3, y, z + 2).setType(AIR);
            world.getBlockAt(x - 4, y, z + 2).setType(AIR);
            world.getBlockAt(x, y, z + 3).setType(AIR);
            world.getBlockAt(x + 1, y, z + 3).setType(AIR);
            world.getBlockAt(x + 2, y, z + 3).setType(AIR);
            world.getBlockAt(x + 3, y, z + 3).setType(AIR);
            world.getBlockAt(x + 4, y, z + 3).setType(AIR);
            world.getBlockAt(x - 1, y, z + 3).setType(AIR);
            world.getBlockAt(x - 2, y, z + 3).setType(AIR);
            world.getBlockAt(x - 3, y, z + 3).setType(AIR);
            world.getBlockAt(x - 4, y, z + 3).setType(AIR);
            world.getBlockAt(x, y, z - 4).setType(AIR);
            world.getBlockAt(x + 1, y, z - 4).setType(AIR);
            world.getBlockAt(x + 2, y, z - 4).setType(AIR);
            world.getBlockAt(x + 3, y, z - 4).setType(AIR);
            world.getBlockAt(x - 1, y, z - 4).setType(AIR);
            world.getBlockAt(x - 2, y, z - 4).setType(AIR);
            world.getBlockAt(x - 3, y, z - 4).setType(AIR);
            world.getBlockAt(x, y, z + 4).setType(AIR);
            world.getBlockAt(x + 1, y, z + 4).setType(AIR);
            world.getBlockAt(x + 2, y, z + 4).setType(AIR);
            world.getBlockAt(x + 3, y, z + 4).setType(AIR);
            world.getBlockAt(x - 1, y, z + 4).setType(AIR);
            world.getBlockAt(x - 2, y, z + 4).setType(AIR);
            world.getBlockAt(x - 3, y, z + 4).setType(AIR);
            world.getBlockAt(x, y, z - 5).setType(AIR);
            world.getBlockAt(x + 1, y, z - 5).setType(AIR);
            world.getBlockAt(x - 1, y, z - 5).setType(AIR);
            world.getBlockAt(x, y, z + 5).setType(AIR);
            world.getBlockAt(x + 1, y, z + 5).setType(AIR);
            world.getBlockAt(x - 1, y, z + 5).setType(AIR);
            world.getBlockAt(x + 1, y + 1, z - 5).setType(AIR); // WALLS V LAYER 1
            world.getBlockAt(x + 1, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x + 2, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x + 3, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x + 3, y + 1, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z - 2).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z - 1).setType(AIR);
            world.getBlockAt(x + 5, y + 1, z - 1).setType(AIR);
            world.getBlockAt(x - 1, y + 1, z - 5).setType(AIR);
            world.getBlockAt(x - 1, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x - 2, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x - 3, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x - 3, y + 1, z - 3).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z - 3).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z - 2).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z - 1).setType(AIR);
            world.getBlockAt(x - 5, y + 1, z - 1).setType(AIR);
            world.getBlockAt(x + 1, y + 1, z + 5).setType(AIR);
            world.getBlockAt(x + 1, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x + 2, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x + 3, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x + 3, y + 1, z + 3).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z + 3).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z + 2).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z + 1).setType(AIR);
            world.getBlockAt(x + 5, y + 1, z + 1).setType(AIR);
            world.getBlockAt(x - 1, y + 1, z + 5).setType(AIR);
            world.getBlockAt(x - 1, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x - 2, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x - 3, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x - 3, y + 1, z + 3).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z + 3).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z + 2).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z + 1).setType(AIR);
            world.getBlockAt(x - 5, y + 1, z + 1).setType(AIR);
            world.getBlockAt(x - 5, y + 1, z).setType(AIR, true);
            world.getBlockAt(x + 5, y + 1, z).setType(AIR, true);
            world.getBlockAt(x, y + 1, z + 5).setType(AIR, true);
            world.getBlockAt(x, y + 1, z - 5).setType(AIR, true);
            world.getBlockAt(x + 1, y + 2, z - 5).setType(AIR); // WALLS LAYER 2 V
            world.getBlockAt(x + 1, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x + 2, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x + 3, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x + 3, y + 2, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z - 2).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z - 1).setType(AIR);
            world.getBlockAt(x + 5, y + 2, z - 1).setType(AIR);
            world.getBlockAt(x - 1, y + 2, z - 5).setType(AIR);
            world.getBlockAt(x - 1, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x - 2, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x - 3, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x - 3, y + 2, z - 3).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z - 3).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z - 2).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z - 1).setType(AIR);
            world.getBlockAt(x - 5, y + 2, z - 1).setType(AIR);
            world.getBlockAt(x + 1, y + 2, z + 5).setType(AIR);
            world.getBlockAt(x + 1, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x + 2, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x + 3, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x + 3, y + 2, z + 3).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z + 3).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z + 2).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z + 1).setType(AIR);
            world.getBlockAt(x + 5, y + 2, z + 1).setType(AIR);
            world.getBlockAt(x - 1, y + 2, z + 5).setType(AIR);
            world.getBlockAt(x - 1, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x - 2, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x - 3, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x - 3, y + 2, z + 3).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z + 3).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z + 2).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z + 1).setType(AIR);
            world.getBlockAt(x - 5, y + 2, z + 1).setType(AIR);
            world.getBlockAt(x - 5, y + 2, z).setType(AIR, true);
            world.getBlockAt(x + 5, y + 2, z).setType(AIR, true);
            world.getBlockAt(x, y + 2, z + 5).setType(AIR, true);
            world.getBlockAt(x, y + 2, z - 5).setType(AIR, true);
            world.getBlockAt(x - 3, y + 3, z + 2).setType(AIR);// ROOF V
            world.getBlockAt(x - 3, y + 3, z + 1).setType(AIR);
            world.getBlockAt(x - 2, y + 3, z + 3).setType(AIR);
            world.getBlockAt(x - 1, y + 3, z + 3).setType(AIR);
            world.getBlockAt(x - 3, y + 3, z - 2).setType(AIR);
            world.getBlockAt(x - 3, y + 3, z - 1).setType(AIR);
            world.getBlockAt(x - 2, y + 3, z - 3).setType(AIR);
            world.getBlockAt(x - 1, y + 3, z - 3).setType(AIR);
            world.getBlockAt(x + 3, y + 3, z + 2).setType(AIR);
            world.getBlockAt(x + 3, y + 3, z + 1).setType(AIR);
            world.getBlockAt(x + 2, y + 3, z + 3).setType(AIR);
            world.getBlockAt(x + 1, y + 3, z + 3).setType(AIR);
            world.getBlockAt(x + 3, y + 3, z - 2).setType(AIR);
            world.getBlockAt(x + 3, y + 3, z - 1).setType(AIR);
            world.getBlockAt(x + 2, y + 3, z - 3).setType(AIR);
            world.getBlockAt(x + 1, y + 3, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y + 3, z).setType(AIR);
            world.getBlockAt(x - 4, y + 3, z).setType(AIR);
            world.getBlockAt(x, y + 3, z + 4).setType(AIR);
            world.getBlockAt(x, y + 3, z - 4).setType(AIR);
        });
    }

    public CompletableFuture<SlimeWorld> fetchWorld() {
        this.plugin.getLogger().info("Fetching World");

        SlimePlugin plugin = (SlimePlugin) Bukkit.getPluginManager().getPlugin("SlimeWorldManager");

        SlimeLoader sqlLoader = plugin.getLoader("mysql");
        String databaseMapName = this.plugin.getConfig().getString("DatabaseMapName");

        // create a new and empty property map
        SlimePropertyMap properties = new SlimePropertyMap();

        properties.setValue(SlimeProperties.DIFFICULTY, "normal");
        properties.setValue(SlimeProperties.SPAWN_X, this.plugin.getConfig().getInt("WorldSpawn.x"));
        properties.setValue(SlimeProperties.SPAWN_Y, this.plugin.getConfig().getInt("WorldSpawn.y"));
        properties.setValue(SlimeProperties.SPAWN_Z, this.plugin.getConfig().getInt("WorldSpawn.z"));

        CompletableFuture<SlimeWorld> callback = new CompletableFuture<>();

        callback.completeAsync(() -> {
            this.plugin.getLogger().warning("Completing Async");
            try {
                world = plugin.loadWorld(sqlLoader, databaseMapName, true, properties);
            } catch (UnknownWorldException | IOException | CorruptedWorldException | NewerFormatException |
                     WorldLockedException e) {
                this.plugin.getLogger().log(Level.SEVERE, "An error occoured whilst fetching map '" + databaseMapName + "' from the database!", e);
            }
            return world;
        });
        return callback;
    }
}