package dev.foxikle.webnetbedwars.managers;

import com.infernalsuite.aswm.api.SlimePlugin;
import com.infernalsuite.aswm.api.exceptions.CorruptedWorldException;
import com.infernalsuite.aswm.api.exceptions.NewerFormatException;
import com.infernalsuite.aswm.api.exceptions.UnknownWorldException;
import com.infernalsuite.aswm.api.exceptions.WorldLockedException;
import com.infernalsuite.aswm.api.loaders.SlimeLoader;
import com.infernalsuite.aswm.api.world.SlimeWorld;
import com.infernalsuite.aswm.api.world.properties.SlimeProperties;
import com.infernalsuite.aswm.api.world.properties.SlimePropertyMap;
import dev.foxikle.webnetbedwars.WebNetBedWars;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.player.PlayerJoinEvent;

import java.io.IOException;
import java.util.logging.Level;

import static org.bukkit.Material.AIR;

public class WorldManager {
    private final WebNetBedWars plugin;
    private final GameManager gameManager;
    private boolean readOnly;

    public WorldManager(WebNetBedWars plugin, GameManager gameManager) {
        this.plugin = plugin;
        this.gameManager = gameManager;
    }

    public void createSpawnPlatform() {
        FileConfiguration config = plugin.getConfig();
        Location loc = config.getLocation("SpawnPlatformCenter");
        int x = (int) loc.getX();
        int y = (int) loc.getY();
        int z = (int) loc.getZ();
        World world = loc.getWorld();
        world.setSpawnLocation(loc);

        Bukkit.getScheduler().runTask(plugin, () -> {
            world.getBlockAt(x, y, z).setType(Material.BEACON);
            world.getBlockAt(x + 1, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 5, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 5, y, z).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 5, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 5, y, z + 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 5, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 5, y, z - 1).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z - 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z - 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z + 2).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 4, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 4, y, z + 3).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z - 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 2, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 3, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 2, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 3, y, z + 4).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z - 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z - 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z - 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x, y, z + 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y, z + 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x - 1, y, z + 5).setType(Material.GRAY_STAINED_GLASS);
            world.getBlockAt(x + 1, y + 1, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE); // WALLS V LAYER 1
            world.getBlockAt(x + 1, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 2, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 1, z - 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x + 4, y + 1, z - 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 1, z - 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 1, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 5, y + 1, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 1, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 2, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 1, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 1, z - 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x - 4, y + 1, z - 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 1, z - 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 1, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 1, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 1, y + 1, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 1, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 2, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 1, z + 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x + 4, y + 1, z + 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 1, z + 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 1, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 5, y + 1, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 1, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 2, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 1, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 1, z + 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x - 4, y + 1, z + 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 1, z + 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 1, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 1, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 1, z).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x + 5, y + 1, z).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x, y + 1, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x, y + 1, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x + 1, y + 2, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE); // WALLS LAYER 2 V
            world.getBlockAt(x + 1, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 2, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 2, z - 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x + 4, y + 2, z - 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 2, z - 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 2, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 5, y + 2, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 2, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 2, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 2, z - 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 2, z - 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x - 4, y + 2, z - 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 2, z - 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 2, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 2, z - 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 1, y + 2, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 1, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 2, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 3, y + 2, z + 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x + 4, y + 2, z + 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 2, z + 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 4, y + 2, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x + 5, y + 2, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 2, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 1, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 2, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 2, z + 4).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 3, y + 2, z + 3).setType(Material.COBBLED_DEEPSLATE_WALL);
            world.getBlockAt(x - 4, y + 2, z + 3).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 2, z + 2).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 4, y + 2, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 2, z + 1).setType(Material.WHITE_STAINED_GLASS_PANE);
            world.getBlockAt(x - 5, y + 2, z).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x + 5, y + 2, z).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x, y + 2, z + 5).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x, y + 2, z - 5).setType(Material.WHITE_STAINED_GLASS_PANE, true);
            world.getBlockAt(x - 3, y + 3, z + 2).setType(Material.DARK_PRISMARINE_SLAB);// ROOF V
            world.getBlockAt(x - 3, y + 3, z + 1).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 2, y + 3, z + 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 1, y + 3, z + 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 3, y + 3, z - 2).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 3, y + 3, z - 1).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 2, y + 3, z - 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 1, y + 3, z - 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 3, y + 3, z + 2).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 3, y + 3, z + 1).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 2, y + 3, z + 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 1, y + 3, z + 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 3, y + 3, z - 2).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 3, y + 3, z - 1).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 2, y + 3, z - 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 1, y + 3, z - 3).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x + 4, y + 3, z).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x - 4, y + 3, z).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x, y + 3, z + 4).setType(Material.DARK_PRISMARINE_SLAB);
            world.getBlockAt(x, y + 3, z - 4).setType(Material.DARK_PRISMARINE_SLAB);
        });
    }

    //fixme use a for loop or recusion to simplify
    public void removeSpawnPlatform() {
        FileConfiguration config = plugin.getConfig();
        Location loc = config.getLocation("SpawnPlatformCenter");
        int x = (int) loc.getX();
        int y = (int) loc.getY();
        int z = (int) loc.getZ();
        World world = loc.getWorld();

        Bukkit.getScheduler().runTask(plugin, () -> {
            world.getBlockAt(x, y, z).setType(AIR);
            world.getBlockAt(x + 1, y, z).setType(AIR);
            world.getBlockAt(x + 2, y, z).setType(AIR);
            world.getBlockAt(x + 3, y, z).setType(AIR);
            world.getBlockAt(x + 4, y, z).setType(AIR);
            world.getBlockAt(x + 5, y, z).setType(AIR);
            world.getBlockAt(x - 1, y, z).setType(AIR);
            world.getBlockAt(x - 2, y, z).setType(AIR);
            world.getBlockAt(x - 3, y, z).setType(AIR);
            world.getBlockAt(x - 4, y, z).setType(AIR);
            world.getBlockAt(x - 5, y, z).setType(AIR);
            world.getBlockAt(x, y, z + 1).setType(AIR);
            world.getBlockAt(x + 1, y, z + 1).setType(AIR);
            world.getBlockAt(x + 2, y, z + 1).setType(AIR);
            world.getBlockAt(x + 3, y, z + 1).setType(AIR);
            world.getBlockAt(x + 4, y, z + 1).setType(AIR);
            world.getBlockAt(x + 5, y, z + 1).setType(AIR);
            world.getBlockAt(x - 1, y, z + 1).setType(AIR);
            world.getBlockAt(x - 2, y, z + 1).setType(AIR);
            world.getBlockAt(x - 3, y, z + 1).setType(AIR);
            world.getBlockAt(x - 4, y, z + 1).setType(AIR);
            world.getBlockAt(x - 5, y, z + 1).setType(AIR);
            world.getBlockAt(x, y, z - 1).setType(AIR);
            world.getBlockAt(x + 1, y, z - 1).setType(AIR);
            world.getBlockAt(x + 2, y, z - 1).setType(AIR);
            world.getBlockAt(x + 3, y, z - 1).setType(AIR);
            world.getBlockAt(x + 4, y, z - 1).setType(AIR);
            world.getBlockAt(x + 5, y, z - 1).setType(AIR);
            world.getBlockAt(x - 1, y, z - 1).setType(AIR);
            world.getBlockAt(x - 2, y, z - 1).setType(AIR);
            world.getBlockAt(x - 3, y, z - 1).setType(AIR);
            world.getBlockAt(x - 4, y, z - 1).setType(AIR);
            world.getBlockAt(x - 5, y, z - 1).setType(AIR);
            world.getBlockAt(x, y, z - 2).setType(AIR);
            world.getBlockAt(x + 1, y, z - 2).setType(AIR);
            world.getBlockAt(x + 2, y, z - 2).setType(AIR);
            world.getBlockAt(x + 3, y, z - 2).setType(AIR);
            world.getBlockAt(x + 4, y, z - 2).setType(AIR);
            world.getBlockAt(x - 1, y, z - 2).setType(AIR);
            world.getBlockAt(x - 2, y, z - 2).setType(AIR);
            world.getBlockAt(x - 3, y, z - 2).setType(AIR);
            world.getBlockAt(x - 4, y, z - 2).setType(AIR);
            world.getBlockAt(x, y, z - 3).setType(AIR);
            world.getBlockAt(x + 1, y, z - 3).setType(AIR);
            world.getBlockAt(x + 2, y, z - 3).setType(AIR);
            world.getBlockAt(x + 3, y, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y, z - 3).setType(AIR);
            world.getBlockAt(x - 1, y, z - 3).setType(AIR);
            world.getBlockAt(x - 2, y, z - 3).setType(AIR);
            world.getBlockAt(x - 3, y, z - 3).setType(AIR);
            world.getBlockAt(x - 4, y, z - 3).setType(AIR);
            world.getBlockAt(x, y, z + 2).setType(AIR);
            world.getBlockAt(x + 1, y, z + 2).setType(AIR);
            world.getBlockAt(x + 2, y, z + 2).setType(AIR);
            world.getBlockAt(x + 3, y, z + 2).setType(AIR);
            world.getBlockAt(x + 4, y, z + 2).setType(AIR);
            world.getBlockAt(x - 1, y, z + 2).setType(AIR);
            world.getBlockAt(x - 2, y, z + 2).setType(AIR);
            world.getBlockAt(x - 3, y, z + 2).setType(AIR);
            world.getBlockAt(x - 4, y, z + 2).setType(AIR);
            world.getBlockAt(x, y, z + 3).setType(AIR);
            world.getBlockAt(x + 1, y, z + 3).setType(AIR);
            world.getBlockAt(x + 2, y, z + 3).setType(AIR);
            world.getBlockAt(x + 3, y, z + 3).setType(AIR);
            world.getBlockAt(x + 4, y, z + 3).setType(AIR);
            world.getBlockAt(x - 1, y, z + 3).setType(AIR);
            world.getBlockAt(x - 2, y, z + 3).setType(AIR);
            world.getBlockAt(x - 3, y, z + 3).setType(AIR);
            world.getBlockAt(x - 4, y, z + 3).setType(AIR);
            world.getBlockAt(x, y, z - 4).setType(AIR);
            world.getBlockAt(x + 1, y, z - 4).setType(AIR);
            world.getBlockAt(x + 2, y, z - 4).setType(AIR);
            world.getBlockAt(x + 3, y, z - 4).setType(AIR);
            world.getBlockAt(x - 1, y, z - 4).setType(AIR);
            world.getBlockAt(x - 2, y, z - 4).setType(AIR);
            world.getBlockAt(x - 3, y, z - 4).setType(AIR);
            world.getBlockAt(x, y, z + 4).setType(AIR);
            world.getBlockAt(x + 1, y, z + 4).setType(AIR);
            world.getBlockAt(x + 2, y, z + 4).setType(AIR);
            world.getBlockAt(x + 3, y, z + 4).setType(AIR);
            world.getBlockAt(x - 1, y, z + 4).setType(AIR);
            world.getBlockAt(x - 2, y, z + 4).setType(AIR);
            world.getBlockAt(x - 3, y, z + 4).setType(AIR);
            world.getBlockAt(x, y, z - 5).setType(AIR);
            world.getBlockAt(x + 1, y, z - 5).setType(AIR);
            world.getBlockAt(x - 1, y, z - 5).setType(AIR);
            world.getBlockAt(x, y, z + 5).setType(AIR);
            world.getBlockAt(x + 1, y, z + 5).setType(AIR);
            world.getBlockAt(x - 1, y, z + 5).setType(AIR);
            world.getBlockAt(x + 1, y + 1, z - 5).setType(AIR); // WALLS V LAYER 1
            world.getBlockAt(x + 1, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x + 2, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x + 3, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x + 3, y + 1, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z - 2).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z - 1).setType(AIR);
            world.getBlockAt(x + 5, y + 1, z - 1).setType(AIR);
            world.getBlockAt(x - 1, y + 1, z - 5).setType(AIR);
            world.getBlockAt(x - 1, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x - 2, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x - 3, y + 1, z - 4).setType(AIR);
            world.getBlockAt(x - 3, y + 1, z - 3).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z - 3).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z - 2).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z - 1).setType(AIR);
            world.getBlockAt(x - 5, y + 1, z - 1).setType(AIR);
            world.getBlockAt(x + 1, y + 1, z + 5).setType(AIR);
            world.getBlockAt(x + 1, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x + 2, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x + 3, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x + 3, y + 1, z + 3).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z + 3).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z + 2).setType(AIR);
            world.getBlockAt(x + 4, y + 1, z + 1).setType(AIR);
            world.getBlockAt(x + 5, y + 1, z + 1).setType(AIR);
            world.getBlockAt(x - 1, y + 1, z + 5).setType(AIR);
            world.getBlockAt(x - 1, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x - 2, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x - 3, y + 1, z + 4).setType(AIR);
            world.getBlockAt(x - 3, y + 1, z + 3).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z + 3).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z + 2).setType(AIR);
            world.getBlockAt(x - 4, y + 1, z + 1).setType(AIR);
            world.getBlockAt(x - 5, y + 1, z + 1).setType(AIR);
            world.getBlockAt(x - 5, y + 1, z).setType(AIR, true);
            world.getBlockAt(x + 5, y + 1, z).setType(AIR, true);
            world.getBlockAt(x, y + 1, z + 5).setType(AIR, true);
            world.getBlockAt(x, y + 1, z - 5).setType(AIR, true);
            world.getBlockAt(x + 1, y + 2, z - 5).setType(AIR); // WALLS LAYER 2 V
            world.getBlockAt(x + 1, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x + 2, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x + 3, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x + 3, y + 2, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z - 2).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z - 1).setType(AIR);
            world.getBlockAt(x + 5, y + 2, z - 1).setType(AIR);
            world.getBlockAt(x - 1, y + 2, z - 5).setType(AIR);
            world.getBlockAt(x - 1, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x - 2, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x - 3, y + 2, z - 4).setType(AIR);
            world.getBlockAt(x - 3, y + 2, z - 3).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z - 3).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z - 2).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z - 1).setType(AIR);
            world.getBlockAt(x - 5, y + 2, z - 1).setType(AIR);
            world.getBlockAt(x + 1, y + 2, z + 5).setType(AIR);
            world.getBlockAt(x + 1, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x + 2, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x + 3, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x + 3, y + 2, z + 3).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z + 3).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z + 2).setType(AIR);
            world.getBlockAt(x + 4, y + 2, z + 1).setType(AIR);
            world.getBlockAt(x + 5, y + 2, z + 1).setType(AIR);
            world.getBlockAt(x - 1, y + 2, z + 5).setType(AIR);
            world.getBlockAt(x - 1, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x - 2, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x - 3, y + 2, z + 4).setType(AIR);
            world.getBlockAt(x - 3, y + 2, z + 3).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z + 3).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z + 2).setType(AIR);
            world.getBlockAt(x - 4, y + 2, z + 1).setType(AIR);
            world.getBlockAt(x - 5, y + 2, z + 1).setType(AIR);
            world.getBlockAt(x - 5, y + 2, z).setType(AIR, true);
            world.getBlockAt(x + 5, y + 2, z).setType(AIR, true);
            world.getBlockAt(x, y + 2, z + 5).setType(AIR, true);
            world.getBlockAt(x, y + 2, z - 5).setType(AIR, true);
            world.getBlockAt(x - 3, y + 3, z + 2).setType(AIR);// ROOF V
            world.getBlockAt(x - 3, y + 3, z + 1).setType(AIR);
            world.getBlockAt(x - 2, y + 3, z + 3).setType(AIR);
            world.getBlockAt(x - 1, y + 3, z + 3).setType(AIR);
            world.getBlockAt(x - 3, y + 3, z - 2).setType(AIR);
            world.getBlockAt(x - 3, y + 3, z - 1).setType(AIR);
            world.getBlockAt(x - 2, y + 3, z - 3).setType(AIR);
            world.getBlockAt(x - 1, y + 3, z - 3).setType(AIR);
            world.getBlockAt(x + 3, y + 3, z + 2).setType(AIR);
            world.getBlockAt(x + 3, y + 3, z + 1).setType(AIR);
            world.getBlockAt(x + 2, y + 3, z + 3).setType(AIR);
            world.getBlockAt(x + 1, y + 3, z + 3).setType(AIR);
            world.getBlockAt(x + 3, y + 3, z - 2).setType(AIR);
            world.getBlockAt(x + 3, y + 3, z - 1).setType(AIR);
            world.getBlockAt(x + 2, y + 3, z - 3).setType(AIR);
            world.getBlockAt(x + 1, y + 3, z - 3).setType(AIR);
            world.getBlockAt(x + 4, y + 3, z).setType(AIR);
            world.getBlockAt(x - 4, y + 3, z).setType(AIR);
            world.getBlockAt(x, y + 3, z + 4).setType(AIR);
            world.getBlockAt(x, y + 3, z - 4).setType(AIR);
        });
    }

    public void loadWorld() {
            {
                SlimePlugin plugin = (SlimePlugin) Bukkit.getPluginManager().getPlugin("SlimeWorldManager");

                SlimeLoader sqlLoader = plugin.getLoader("mysql");

                // create a new and empty property map
                SlimePropertyMap properties = new SlimePropertyMap();

                properties.setString(SlimeProperties.DIFFICULTY, "normal");
                properties.setInt(SlimeProperties.SPAWN_X, 123);
                properties.setInt(SlimeProperties.SPAWN_Y, 112);
                properties.setInt(SlimeProperties.SPAWN_Z, 170);
// add as many as you would like

                try {
                    // note that this method should be called asynchronously
                    SlimeWorld world = plugin.loadWorld(sqlLoader, "skywars", readOnly, properties);

                    // note that this method must be called synchronously
                    plugin.loadWorld(world);
                } catch (UnknownWorldException | IOException | CorruptedWorldException | NewerFormatException |
                         WorldLockedException exception) {
                }
            }
        }
    }