package net.cytonic.cytonicbedwars.managers;

import lombok.NoArgsConstructor;
import net.cytonic.cytonicbedwars.Config;
import net.cytonic.cytonicbedwars.data.objects.Team;
import net.cytonic.cytosis.Cytosis;
import net.cytonic.cytosis.logging.Logger;
import net.hollowcube.polar.PolarLoader;
import net.minestom.server.coordinate.BlockVec;
import net.minestom.server.coordinate.Pos;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockFace;

@NoArgsConstructor
public class WorldManager {

    public void breakBed(Team team) {
        Block block = Cytosis.getDefaultInstance().getBlock(team.getBedLocation());
        BlockVec blockPos = new BlockVec(team.getBedLocation());
        if (block.key().equals(team.getBedType().key())) {
            Cytosis.getDefaultInstance().setBlock(blockPos, Block.AIR);
            BlockFace facing = BlockFace.valueOf(block.getProperty("facing").toUpperCase());
            if (block.getProperty("part").equals("head")) {
                facing = facing.getOppositeFace();
            }
            Cytosis.getDefaultInstance().setBlock(blockPos.relative(facing), Block.AIR);
        }
    }

    public void loadWorld() {
        try {
            //fixme
//            var dimKey = MinecraftServer.getDimensionTypeRegistry().register("bedwars:" + Config.worldName, DimensionType.builder().ambientLight(100).build());
            Cytosis.setDefaultInstance(Cytosis.getMinestomInstanceManager().createInstanceContainer());
            Cytosis.getDatabaseManager().getMysqlDatabase().getWorld(Config.worldName, "bedwars_map_" + Config.mode.toLowerCase())
                    .whenComplete((world, throwable) -> {
                        if (throwable != null) {
                            Logger.error("error", throwable);
                        } else {
                            Cytosis.setDefaultInstance(Cytosis.getMinestomInstanceManager().createInstanceContainer());
                            Cytosis.getDefaultInstance().setChunkLoader(new PolarLoader(world));
                            Cytosis.getDefaultInstance().setTimeRate(0);
                            Cytosis.getDefaultInstance().setTime(6000);
                            Logger.info("loading spawn platform");
                            createSpawnPlatform();
                        }
                    });

        } catch (Exception e) {
            Logger.error("error", e);
        }
    }

    public void redoWorld() {
        loadWorld();
        createSpawnPlatform();
    }

    public void createSpawnPlatform() {
        Pos loc = Config.spawnPlatformCenter;
        int x = (int) loc.x();
        int y = (int) loc.y();
        int z = (int) loc.z();
        Cytosis.getDefaultInstance().setBlock(x, y, z, Block.BEACON);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 5, y, z, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 5, y, z, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 5, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 5, y, z + 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 5, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 5, y, z - 1, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x, y, z - 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z - 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z - 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z - 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z - 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z - 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z - 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z - 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z - 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x, y, z - 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z - 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z - 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z - 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z - 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z - 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z - 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z - 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z - 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x, y, z + 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z + 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z + 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z + 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z + 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z + 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z + 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z + 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z + 2, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x, y, z + 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z + 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z + 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z + 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z + 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z + 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z + 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z + 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z + 3, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x, y, z - 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z - 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z - 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z - 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z - 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z - 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z - 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x, y, z + 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z + 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z + 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z + 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z + 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z + 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z + 4, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x, y, z - 5, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z - 5, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z - 5, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x, y, z + 5, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z + 5, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z + 5, Block.GRAY_STAINED_GLASS);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 1, z - 5, Block.WHITE_STAINED_GLASS_PANE); // WALLS V LAYER 1
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 1, z - 3, Block.COBBLED_DEEPSLATE_WALL);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z - 3, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z - 2, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z - 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 1, z - 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 1, z - 5, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 1, z - 3, Block.COBBLED_DEEPSLATE_WALL);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z - 3, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z - 2, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z - 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 1, z - 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 1, z + 5, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 1, z + 3, Block.COBBLED_DEEPSLATE_WALL);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z + 3, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z + 2, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z + 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 1, z + 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 1, z + 5, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 1, z + 3, Block.COBBLED_DEEPSLATE_WALL);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z + 3, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z + 2, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z + 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 1, z + 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 1, z, Block.WHITE_STAINED_GLASS_PANE, true);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 1, z, Block.WHITE_STAINED_GLASS_PANE, true);
        Cytosis.getDefaultInstance().setBlock(x, y + 1, z + 5, Block.WHITE_STAINED_GLASS_PANE, true);
        Cytosis.getDefaultInstance().setBlock(x, y + 1, z - 5, Block.WHITE_STAINED_GLASS_PANE, true);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 2, z - 5, Block.WHITE_STAINED_GLASS_PANE); // WALLS LAYER 2 V
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 2, z - 3, Block.COBBLED_DEEPSLATE_WALL);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z - 3, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z - 2, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z - 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 2, z - 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 2, z - 5, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 2, z - 3, Block.COBBLED_DEEPSLATE_WALL);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z - 3, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z - 2, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z - 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 2, z - 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 2, z + 5, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 2, z + 3, Block.COBBLED_DEEPSLATE_WALL);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z + 3, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z + 2, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z + 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 2, z + 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 2, z + 5, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 2, z + 3, Block.COBBLED_DEEPSLATE_WALL);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z + 3, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z + 2, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z + 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 2, z + 1, Block.WHITE_STAINED_GLASS_PANE);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 2, z, Block.WHITE_STAINED_GLASS_PANE, true);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 2, z, Block.WHITE_STAINED_GLASS_PANE, true);
        Cytosis.getDefaultInstance().setBlock(x, y + 2, z + 5, Block.WHITE_STAINED_GLASS_PANE, true);
        Cytosis.getDefaultInstance().setBlock(x, y + 2, z - 5, Block.WHITE_STAINED_GLASS_PANE, true);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 3, z + 2, Block.DARK_PRISMARINE_SLAB);// ROOF V
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 3, z + 1, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 3, z + 3, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 3, z + 3, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 3, z - 2, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 3, z - 1, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 3, z - 3, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 3, z - 3, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 3, z + 2, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 3, z + 1, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 3, z + 3, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 3, z + 3, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 3, z - 2, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 3, z - 1, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 3, z - 3, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 3, z - 3, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 3, z, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 3, z, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x, y + 3, z + 4, Block.DARK_PRISMARINE_SLAB);
        Cytosis.getDefaultInstance().setBlock(x, y + 3, z - 4, Block.DARK_PRISMARINE_SLAB);
    }

    //fixme use a for loop or recursion to simplify
    public void removeSpawnPlatform() {
        Pos loc = Config.spawnPlatformCenter;
        int x = (int) loc.x();
        int y = (int) loc.y();
        int z = (int) loc.z();
        Cytosis.getDefaultInstance().setBlock(x, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 5, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 5, y, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 5, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 5, y, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 5, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 5, y, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y, z - 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z - 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z - 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y, z + 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y, z + 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y, z + 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 1, z - 5, Block.AIR); // WALLS V LAYER 1
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 1, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 1, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 1, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 1, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 1, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 1, z - 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 1, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 1, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 1, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 1, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 1, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 1, z + 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 1, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 1, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 1, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 1, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 1, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 1, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 1, z + 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 1, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 1, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 1, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 1, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 1, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 1, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 1, z, Block.AIR, true);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 1, z, Block.AIR, true);
        Cytosis.getDefaultInstance().setBlock(x, y + 1, z + 5, Block.AIR, true);
        Cytosis.getDefaultInstance().setBlock(x, y + 1, z - 5, Block.AIR, true);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 2, z - 5, Block.AIR); // WALLS LAYER 2 V
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 2, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 2, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 2, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 2, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 2, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 2, z - 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 2, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 2, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 2, z - 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 2, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 2, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 2, z + 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 2, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 2, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 2, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 2, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 2, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 2, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 2, z + 5, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 2, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 2, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 2, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 2, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 2, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 2, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 5, y + 2, z, Block.AIR, true);
        Cytosis.getDefaultInstance().setBlock(x + 5, y + 2, z, Block.AIR, true);
        Cytosis.getDefaultInstance().setBlock(x, y + 2, z + 5, Block.AIR, true);
        Cytosis.getDefaultInstance().setBlock(x, y + 2, z - 5, Block.AIR, true);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 3, z + 2, Block.AIR);// ROOF V
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 3, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 3, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 3, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 3, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 3, y + 3, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 2, y + 3, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 1, y + 3, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 3, z + 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 3, z + 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 3, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 3, z + 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 3, z - 2, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 3, y + 3, z - 1, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 2, y + 3, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 1, y + 3, z - 3, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x + 4, y + 3, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x - 4, y + 3, z, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y + 3, z + 4, Block.AIR);
        Cytosis.getDefaultInstance().setBlock(x, y + 3, z - 4, Block.AIR);
    }
}