package net.cytonic.cytonicbedwars.managers;

import net.cytonic.cytonicbedwars.CytonicBedWars;
import net.cytonic.cytosis.Cytosis;
import net.hollowcube.polar.PolarLoader;
import net.hollowcube.polar.PolarWorld;
import net.minestom.server.MinecraftServer;
import net.minestom.server.coordinate.Pos;
import net.minestom.server.instance.Instance;
import net.minestom.server.instance.LightingChunk;
import net.minestom.server.instance.block.Block;

import java.util.concurrent.ExecutionException;

public class WorldManager {

    public WorldManager() {}

    public void createSpawnPlatform() {
        Pos loc = new Pos(0, 0, 0);
        int x = (int) loc.x();
        int y = (int) loc.y();
        int z = (int) loc.z();
        Instance world = Cytosis.getDefaultInstance();

        MinecraftServer.getSchedulerManager().buildTask(() -> {
            world.setBlock(x, y, z, Block.BEACON);
            world.setBlock(x + 1, y, z, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 2, y, z, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 3, y, z, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 4, y, z, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 5, y, z, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 2, y, z, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 3, y, z, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 4, y, z, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 5, y, z, Block.GRAY_STAINED_GLASS);
            world.setBlock(x, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 2, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 3, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 4, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 5, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 2, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 3, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 4, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 5, y, z + 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 2, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 3, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 4, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 5, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 2, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 3, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 4, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 5, y, z - 1, Block.GRAY_STAINED_GLASS);
            world.setBlock(x, y, z - 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y, z - 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 2, y, z - 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 3, y, z - 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 4, y, z - 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z - 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 2, y, z - 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 3, y, z - 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 4, y, z - 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x, y, z - 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y, z - 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 2, y, z - 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 3, y, z - 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 4, y, z - 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z - 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 2, y, z - 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 3, y, z - 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 4, y, z - 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x, y, z + 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y, z + 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 2, y, z + 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 3, y, z + 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 4, y, z + 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z + 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 2, y, z + 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 3, y, z + 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 4, y, z + 2, Block.GRAY_STAINED_GLASS);
            world.setBlock(x, y, z + 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y, z + 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 2, y, z + 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 3, y, z + 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 4, y, z + 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z + 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 2, y, z + 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 3, y, z + 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 4, y, z + 3, Block.GRAY_STAINED_GLASS);
            world.setBlock(x, y, z - 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y, z - 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 2, y, z - 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 3, y, z - 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z - 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 2, y, z - 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 3, y, z - 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x, y, z + 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y, z + 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 2, y, z + 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 3, y, z + 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z + 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 2, y, z + 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 3, y, z + 4, Block.GRAY_STAINED_GLASS);
            world.setBlock(x, y, z - 5, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y, z - 5, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z - 5, Block.GRAY_STAINED_GLASS);
            world.setBlock(x, y, z + 5, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y, z + 5, Block.GRAY_STAINED_GLASS);
            world.setBlock(x - 1, y, z + 5, Block.GRAY_STAINED_GLASS);
            world.setBlock(x + 1, y + 1, z - 5, Block.WHITE_STAINED_GLASS_PANE); // WALLS V LAYER 1
            world.setBlock(x + 1, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 2, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 3, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 3, y + 1, z - 3, Block.COBBLED_DEEPSLATE_WALL);
            world.setBlock(x + 4, y + 1, z - 3, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 4, y + 1, z - 2, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 4, y + 1, z - 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 5, y + 1, z - 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 1, y + 1, z - 5, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 1, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 2, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 3, y + 1, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 3, y + 1, z - 3, Block.COBBLED_DEEPSLATE_WALL);
            world.setBlock(x - 4, y + 1, z - 3, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 4, y + 1, z - 2, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 4, y + 1, z - 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 5, y + 1, z - 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 1, y + 1, z + 5, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 1, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 2, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 3, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 3, y + 1, z + 3, Block.COBBLED_DEEPSLATE_WALL);
            world.setBlock(x + 4, y + 1, z + 3, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 4, y + 1, z + 2, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 4, y + 1, z + 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 5, y + 1, z + 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 1, y + 1, z + 5, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 1, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 2, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 3, y + 1, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 3, y + 1, z + 3, Block.COBBLED_DEEPSLATE_WALL);
            world.setBlock(x - 4, y + 1, z + 3, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 4, y + 1, z + 2, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 4, y + 1, z + 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 5, y + 1, z + 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 5, y + 1, z, Block.WHITE_STAINED_GLASS_PANE, true);
            world.setBlock(x + 5, y + 1, z, Block.WHITE_STAINED_GLASS_PANE, true);
            world.setBlock(x, y + 1, z + 5, Block.WHITE_STAINED_GLASS_PANE, true);
            world.setBlock(x, y + 1, z - 5, Block.WHITE_STAINED_GLASS_PANE, true);
            world.setBlock(x + 1, y + 2, z - 5, Block.WHITE_STAINED_GLASS_PANE); // WALLS LAYER 2 V
            world.setBlock(x + 1, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 2, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 3, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 3, y + 2, z - 3, Block.COBBLED_DEEPSLATE_WALL);
            world.setBlock(x + 4, y + 2, z - 3, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 4, y + 2, z - 2, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 4, y + 2, z - 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 5, y + 2, z - 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 1, y + 2, z - 5, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 1, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 2, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 3, y + 2, z - 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 3, y + 2, z - 3, Block.COBBLED_DEEPSLATE_WALL);
            world.setBlock(x - 4, y + 2, z - 3, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 4, y + 2, z - 2, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 4, y + 2, z - 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 5, y + 2, z - 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 1, y + 2, z + 5, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 1, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 2, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 3, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 3, y + 2, z + 3, Block.COBBLED_DEEPSLATE_WALL);
            world.setBlock(x + 4, y + 2, z + 3, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 4, y + 2, z + 2, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 4, y + 2, z + 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x + 5, y + 2, z + 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 1, y + 2, z + 5, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 1, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 2, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 3, y + 2, z + 4, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 3, y + 2, z + 3, Block.COBBLED_DEEPSLATE_WALL);
            world.setBlock(x - 4, y + 2, z + 3, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 4, y + 2, z + 2, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 4, y + 2, z + 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 5, y + 2, z + 1, Block.WHITE_STAINED_GLASS_PANE);
            world.setBlock(x - 5, y + 2, z, Block.WHITE_STAINED_GLASS_PANE, true);
            world.setBlock(x + 5, y + 2, z, Block.WHITE_STAINED_GLASS_PANE, true);
            world.setBlock(x, y + 2, z + 5, Block.WHITE_STAINED_GLASS_PANE, true);
            world.setBlock(x, y + 2, z - 5, Block.WHITE_STAINED_GLASS_PANE, true);
            world.setBlock(x - 3, y + 3, z + 2, Block.DARK_PRISMARINE_SLAB);// ROOF V
            world.setBlock(x - 3, y + 3, z + 1, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x - 2, y + 3, z + 3, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x - 1, y + 3, z + 3, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x - 3, y + 3, z - 2, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x - 3, y + 3, z - 1, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x - 2, y + 3, z - 3, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x - 1, y + 3, z - 3, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x + 3, y + 3, z + 2, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x + 3, y + 3, z + 1, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x + 2, y + 3, z + 3, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x + 1, y + 3, z + 3, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x + 3, y + 3, z - 2, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x + 3, y + 3, z - 1, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x + 2, y + 3, z - 3, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x + 1, y + 3, z - 3, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x + 4, y + 3, z, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x - 4, y + 3, z, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x, y + 3, z + 4, Block.DARK_PRISMARINE_SLAB);
            world.setBlock(x, y + 3, z - 4, Block.DARK_PRISMARINE_SLAB);
        });
    }

    //fixme use a for loop or recusion to simplify
    public void removeSpawnPlatform() {
        Pos loc = new Pos(0, 0, 0);
        int x = (int) loc.x();
        int y = (int) loc.y();
        int z = (int) loc.z();
        Instance world = Cytosis.getDefaultInstance();

        MinecraftServer.getSchedulerManager().buildTask(() -> {
            world.setBlock(x, y, z, Block.AIR);
            world.setBlock(x + 1, y, z, Block.AIR);
            world.setBlock(x + 2, y, z, Block.AIR);
            world.setBlock(x + 3, y, z, Block.AIR);
            world.setBlock(x + 4, y, z, Block.AIR);
            world.setBlock(x + 5, y, z, Block.AIR);
            world.setBlock(x - 1, y, z, Block.AIR);
            world.setBlock(x - 2, y, z, Block.AIR);
            world.setBlock(x - 3, y, z, Block.AIR);
            world.setBlock(x - 4, y, z, Block.AIR);
            world.setBlock(x - 5, y, z, Block.AIR);
            world.setBlock(x, y, z + 1, Block.AIR);
            world.setBlock(x + 1, y, z + 1, Block.AIR);
            world.setBlock(x + 2, y, z + 1, Block.AIR);
            world.setBlock(x + 3, y, z + 1, Block.AIR);
            world.setBlock(x + 4, y, z + 1, Block.AIR);
            world.setBlock(x + 5, y, z + 1, Block.AIR);
            world.setBlock(x - 1, y, z + 1, Block.AIR);
            world.setBlock(x - 2, y, z + 1, Block.AIR);
            world.setBlock(x - 3, y, z + 1, Block.AIR);
            world.setBlock(x - 4, y, z + 1, Block.AIR);
            world.setBlock(x - 5, y, z + 1, Block.AIR);
            world.setBlock(x, y, z - 1, Block.AIR);
            world.setBlock(x + 1, y, z - 1, Block.AIR);
            world.setBlock(x + 2, y, z - 1, Block.AIR);
            world.setBlock(x + 3, y, z - 1, Block.AIR);
            world.setBlock(x + 4, y, z - 1, Block.AIR);
            world.setBlock(x + 5, y, z - 1, Block.AIR);
            world.setBlock(x - 1, y, z - 1, Block.AIR);
            world.setBlock(x - 2, y, z - 1, Block.AIR);
            world.setBlock(x - 3, y, z - 1, Block.AIR);
            world.setBlock(x - 4, y, z - 1, Block.AIR);
            world.setBlock(x - 5, y, z - 1, Block.AIR);
            world.setBlock(x, y, z - 2, Block.AIR);
            world.setBlock(x + 1, y, z - 2, Block.AIR);
            world.setBlock(x + 2, y, z - 2, Block.AIR);
            world.setBlock(x + 3, y, z - 2, Block.AIR);
            world.setBlock(x + 4, y, z - 2, Block.AIR);
            world.setBlock(x - 1, y, z - 2, Block.AIR);
            world.setBlock(x - 2, y, z - 2, Block.AIR);
            world.setBlock(x - 3, y, z - 2, Block.AIR);
            world.setBlock(x - 4, y, z - 2, Block.AIR);
            world.setBlock(x, y, z - 3, Block.AIR);
            world.setBlock(x + 1, y, z - 3, Block.AIR);
            world.setBlock(x + 2, y, z - 3, Block.AIR);
            world.setBlock(x + 3, y, z - 3, Block.AIR);
            world.setBlock(x + 4, y, z - 3, Block.AIR);
            world.setBlock(x - 1, y, z - 3, Block.AIR);
            world.setBlock(x - 2, y, z - 3, Block.AIR);
            world.setBlock(x - 3, y, z - 3, Block.AIR);
            world.setBlock(x - 4, y, z - 3, Block.AIR);
            world.setBlock(x, y, z + 2, Block.AIR);
            world.setBlock(x + 1, y, z + 2, Block.AIR);
            world.setBlock(x + 2, y, z + 2, Block.AIR);
            world.setBlock(x + 3, y, z + 2, Block.AIR);
            world.setBlock(x + 4, y, z + 2, Block.AIR);
            world.setBlock(x - 1, y, z + 2, Block.AIR);
            world.setBlock(x - 2, y, z + 2, Block.AIR);
            world.setBlock(x - 3, y, z + 2, Block.AIR);
            world.setBlock(x - 4, y, z + 2, Block.AIR);
            world.setBlock(x, y, z + 3, Block.AIR);
            world.setBlock(x + 1, y, z + 3, Block.AIR);
            world.setBlock(x + 2, y, z + 3, Block.AIR);
            world.setBlock(x + 3, y, z + 3, Block.AIR);
            world.setBlock(x + 4, y, z + 3, Block.AIR);
            world.setBlock(x - 1, y, z + 3, Block.AIR);
            world.setBlock(x - 2, y, z + 3, Block.AIR);
            world.setBlock(x - 3, y, z + 3, Block.AIR);
            world.setBlock(x - 4, y, z + 3, Block.AIR);
            world.setBlock(x, y, z - 4, Block.AIR);
            world.setBlock(x + 1, y, z - 4, Block.AIR);
            world.setBlock(x + 2, y, z - 4, Block.AIR);
            world.setBlock(x + 3, y, z - 4, Block.AIR);
            world.setBlock(x - 1, y, z - 4, Block.AIR);
            world.setBlock(x - 2, y, z - 4, Block.AIR);
            world.setBlock(x - 3, y, z - 4, Block.AIR);
            world.setBlock(x, y, z + 4, Block.AIR);
            world.setBlock(x + 1, y, z + 4, Block.AIR);
            world.setBlock(x + 2, y, z + 4, Block.AIR);
            world.setBlock(x + 3, y, z + 4, Block.AIR);
            world.setBlock(x - 1, y, z + 4, Block.AIR);
            world.setBlock(x - 2, y, z + 4, Block.AIR);
            world.setBlock(x - 3, y, z + 4, Block.AIR);
            world.setBlock(x, y, z - 5, Block.AIR);
            world.setBlock(x + 1, y, z - 5, Block.AIR);
            world.setBlock(x - 1, y, z - 5, Block.AIR);
            world.setBlock(x, y, z + 5, Block.AIR);
            world.setBlock(x + 1, y, z + 5, Block.AIR);
            world.setBlock(x - 1, y, z + 5, Block.AIR);
            world.setBlock(x + 1, y + 1, z - 5, Block.AIR); // WALLS V LAYER 1
            world.setBlock(x + 1, y + 1, z - 4, Block.AIR);
            world.setBlock(x + 2, y + 1, z - 4, Block.AIR);
            world.setBlock(x + 3, y + 1, z - 4, Block.AIR);
            world.setBlock(x + 3, y + 1, z - 3, Block.AIR);
            world.setBlock(x + 4, y + 1, z - 3, Block.AIR);
            world.setBlock(x + 4, y + 1, z - 2, Block.AIR);
            world.setBlock(x + 4, y + 1, z - 1, Block.AIR);
            world.setBlock(x + 5, y + 1, z - 1, Block.AIR);
            world.setBlock(x - 1, y + 1, z - 5, Block.AIR);
            world.setBlock(x - 1, y + 1, z - 4, Block.AIR);
            world.setBlock(x - 2, y + 1, z - 4, Block.AIR);
            world.setBlock(x - 3, y + 1, z - 4, Block.AIR);
            world.setBlock(x - 3, y + 1, z - 3, Block.AIR);
            world.setBlock(x - 4, y + 1, z - 3, Block.AIR);
            world.setBlock(x - 4, y + 1, z - 2, Block.AIR);
            world.setBlock(x - 4, y + 1, z - 1, Block.AIR);
            world.setBlock(x - 5, y + 1, z - 1, Block.AIR);
            world.setBlock(x + 1, y + 1, z + 5, Block.AIR);
            world.setBlock(x + 1, y + 1, z + 4, Block.AIR);
            world.setBlock(x + 2, y + 1, z + 4, Block.AIR);
            world.setBlock(x + 3, y + 1, z + 4, Block.AIR);
            world.setBlock(x + 3, y + 1, z + 3, Block.AIR);
            world.setBlock(x + 4, y + 1, z + 3, Block.AIR);
            world.setBlock(x + 4, y + 1, z + 2, Block.AIR);
            world.setBlock(x + 4, y + 1, z + 1, Block.AIR);
            world.setBlock(x + 5, y + 1, z + 1, Block.AIR);
            world.setBlock(x - 1, y + 1, z + 5, Block.AIR);
            world.setBlock(x - 1, y + 1, z + 4, Block.AIR);
            world.setBlock(x - 2, y + 1, z + 4, Block.AIR);
            world.setBlock(x - 3, y + 1, z + 4, Block.AIR);
            world.setBlock(x - 3, y + 1, z + 3, Block.AIR);
            world.setBlock(x - 4, y + 1, z + 3, Block.AIR);
            world.setBlock(x - 4, y + 1, z + 2, Block.AIR);
            world.setBlock(x - 4, y + 1, z + 1, Block.AIR);
            world.setBlock(x - 5, y + 1, z + 1, Block.AIR);
            world.setBlock(x - 5, y + 1, z, Block.AIR, true);
            world.setBlock(x + 5, y + 1, z, Block.AIR, true);
            world.setBlock(x, y + 1, z + 5, Block.AIR, true);
            world.setBlock(x, y + 1, z - 5, Block.AIR, true);
            world.setBlock(x + 1, y + 2, z - 5, Block.AIR); // WALLS LAYER 2 V
            world.setBlock(x + 1, y + 2, z - 4, Block.AIR);
            world.setBlock(x + 2, y + 2, z - 4, Block.AIR);
            world.setBlock(x + 3, y + 2, z - 4, Block.AIR);
            world.setBlock(x + 3, y + 2, z - 3, Block.AIR);
            world.setBlock(x + 4, y + 2, z - 3, Block.AIR);
            world.setBlock(x + 4, y + 2, z - 2, Block.AIR);
            world.setBlock(x + 4, y + 2, z - 1, Block.AIR);
            world.setBlock(x + 5, y + 2, z - 1, Block.AIR);
            world.setBlock(x - 1, y + 2, z - 5, Block.AIR);
            world.setBlock(x - 1, y + 2, z - 4, Block.AIR);
            world.setBlock(x - 2, y + 2, z - 4, Block.AIR);
            world.setBlock(x - 3, y + 2, z - 4, Block.AIR);
            world.setBlock(x - 3, y + 2, z - 3, Block.AIR);
            world.setBlock(x - 4, y + 2, z - 3, Block.AIR);
            world.setBlock(x - 4, y + 2, z - 2, Block.AIR);
            world.setBlock(x - 4, y + 2, z - 1, Block.AIR);
            world.setBlock(x - 5, y + 2, z - 1, Block.AIR);
            world.setBlock(x + 1, y + 2, z + 5, Block.AIR);
            world.setBlock(x + 1, y + 2, z + 4, Block.AIR);
            world.setBlock(x + 2, y + 2, z + 4, Block.AIR);
            world.setBlock(x + 3, y + 2, z + 4, Block.AIR);
            world.setBlock(x + 3, y + 2, z + 3, Block.AIR);
            world.setBlock(x + 4, y + 2, z + 3, Block.AIR);
            world.setBlock(x + 4, y + 2, z + 2, Block.AIR);
            world.setBlock(x + 4, y + 2, z + 1, Block.AIR);
            world.setBlock(x + 5, y + 2, z + 1, Block.AIR);
            world.setBlock(x - 1, y + 2, z + 5, Block.AIR);
            world.setBlock(x - 1, y + 2, z + 4, Block.AIR);
            world.setBlock(x - 2, y + 2, z + 4, Block.AIR);
            world.setBlock(x - 3, y + 2, z + 4, Block.AIR);
            world.setBlock(x - 3, y + 2, z + 3, Block.AIR);
            world.setBlock(x - 4, y + 2, z + 3, Block.AIR);
            world.setBlock(x - 4, y + 2, z + 2, Block.AIR);
            world.setBlock(x - 4, y + 2, z + 1, Block.AIR);
            world.setBlock(x - 5, y + 2, z + 1, Block.AIR);
            world.setBlock(x - 5, y + 2, z, Block.AIR, true);
            world.setBlock(x + 5, y + 2, z, Block.AIR, true);
            world.setBlock(x, y + 2, z + 5, Block.AIR, true);
            world.setBlock(x, y + 2, z - 5, Block.AIR, true);
            world.setBlock(x - 3, y + 3, z + 2, Block.AIR);// ROOF V
            world.setBlock(x - 3, y + 3, z + 1, Block.AIR);
            world.setBlock(x - 2, y + 3, z + 3, Block.AIR);
            world.setBlock(x - 1, y + 3, z + 3, Block.AIR);
            world.setBlock(x - 3, y + 3, z - 2, Block.AIR);
            world.setBlock(x - 3, y + 3, z - 1, Block.AIR);
            world.setBlock(x - 2, y + 3, z - 3, Block.AIR);
            world.setBlock(x - 1, y + 3, z - 3, Block.AIR);
            world.setBlock(x + 3, y + 3, z + 2, Block.AIR);
            world.setBlock(x + 3, y + 3, z + 1, Block.AIR);
            world.setBlock(x + 2, y + 3, z + 3, Block.AIR);
            world.setBlock(x + 1, y + 3, z + 3, Block.AIR);
            world.setBlock(x + 3, y + 3, z - 2, Block.AIR);
            world.setBlock(x + 3, y + 3, z - 1, Block.AIR);
            world.setBlock(x + 2, y + 3, z - 3, Block.AIR);
            world.setBlock(x + 1, y + 3, z - 3, Block.AIR);
            world.setBlock(x + 4, y + 3, z, Block.AIR);
            world.setBlock(x - 4, y + 3, z, Block.AIR);
            world.setBlock(x, y + 3, z + 4, Block.AIR);
            world.setBlock(x, y + 3, z - 4, Block.AIR);
        });
    }

    public void loadWorld() {
        try {
            PolarWorld world = Cytosis.getDatabaseManager().getMysqlDatabase().getWorld("").get();
            Cytosis.getDefaultInstance().setChunkLoader(new PolarLoader(world));
            Cytosis.getDefaultInstance().setChunkSupplier(LightingChunk::new);
        } catch (InterruptedException | ExecutionException e) {
            throw new RuntimeException(e);
        }
    }
}