name: Build and push Docker Image
run-name: Deploy Docker Image by @${{ github.actor }}

env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'cytonicmc/CytonicBedwars'
    runs-on: ubuntu-latest
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble
        run: ./gradlew assemble

      - name: Login to GHCR
        run: echo $GHCR_TOKEN | docker login ghcr.io -u CytonicMC --password-stdin

      - name: Build and push Docker Image for multiple platforms
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/cytonicmc/cytonic_bedwars:latest -f docker/Dockerfile . --push

    


